### ISSUE TITLE
X-Arcade .ino files naming confusion 

### ISSUE THREAD

**Issue by Ntemis** [mcgurk/Arduino-USB-HID-RetroJoystickAdapter#4]
Hi, just found out your project and i was thrilled to know that i could get to use my old dual x-arcade working through ps2 to usb adapter but i quite didnt get what is the difference with the two .ino files
in the project dir
x-arcade.ino & x-arcade_c64.ino
Can you please clear it up for me so i can flash away? Thanks

**Comment by mcgurk** [comment]
x-arcade.ino is for USB-adapter. x-arcade_c64.ino is for using X-Arcade with real Commodore 64 home computer. So you probably are interested only of x-arcade.ino.

**Comment by Ntemis** [comment]
You rock! thank you
