### ISSUE TITLE
The Joystick2 library can only be used with a USB MCU

### ISSUE THREAD

**Issue by uxigene** [mcgurk/Arduino-USB-HID-RetroJoystickAdapter#5]
Hello, I'm trying to compile the x-arcade.ino but I'm getting the following error:

```
x-arcade:59: error: #error The Joystick2 library can only be used with a USB MCU (e.g. Arduino Leonardo, Arduino Micro, etc.).
 #error The Joystick2 library can only be used with a USB MCU (e.g. Arduino Leonardo, Arduino Micro, etc.).
  ^
x-arcade:63: error: #error "legacy HID core (non pluggable)"
 #error "legacy HID core (non pluggable)"
  ^
exit status 1
#error The Joystick2 library can only be used with a USB MCU (e.g. Arduino Leonardo, Arduino Micro, etc.).
```

I'm using Arduino Nano V3, HID version 1.0.0 and HID-Project 2.4.4

Can you help me?

**Comment by uxigene** [comment]
Ok, the problem was with HoodLoader2. Problem gone after installation. But still not able to compile. Is there any possibility to compile it for CH3400 ?

**Comment by NetBUG** [comment]
Hi! Nope, CH340 is a dedicated USB-to-Serial chip, and does not emulate HID devices. You need a Pro Micro or any other board with Mega32U4 (Mega16U4 might work as well)
